title = "Flaghunt"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 0                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Rules"
    url = "/rules/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[languages]
[languages.en]
title = "Dingesen"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
# [languages.fr]
# title = "Ananke Fr"
# weight = 2
# contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
cover_dimming_class = "bg-black-10"
featured_image_class = "cover bg-center vh-75"
recent_posts_number = 1
 
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"